### ISSUE TITLE
'par2deep' object has no attribute 'directory'

### ISSUE THREAD

**Issue by alanfranz** [brenthuisman/par2deep#17]
Hello, I get that error when trying to run par2deep on Ubuntu Linux 18.04, Python 3.7. Full install log & traceback follows:

```
alan@microserver:~$ virtualenv -p /usr/bin/python3.7 par2deep-env
Running virtualenv with interpreter /usr/bin/python3.7
Already using interpreter /usr/bin/python3.7
Using base prefix '/usr'
New python executable in /home/alan/par2deep-env/bin/python3.7
Also creating executable in /home/alan/par2deep-env/bin/python
Installing setuptools, pip, wheel...
done.
alan@microserver:~$ par2deep-env/bin/pip install par2deep
Collecting par2deep
  Using cached par2deep-1.9.5.1-py3-none-any.whl (1.8 MB)
Collecting configargparse
  Using cached ConfigArgParse-1.2.3.tar.gz (42 kB)
Collecting PyQt5
  Using cached PyQt5-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux2014_x86_64.whl (68.3 MB)
Collecting PyQt5-sip<13,>=12.8
  Downloading PyQt5_sip-12.8.1-cp37-cp37m-manylinux1_x86_64.whl (283 kB)
     |████████████████████████████████| 283 kB 2.7 MB/s
Collecting Send2Trash
  Using cached Send2Trash-1.5.0-py3-none-any.whl (12 kB)
Collecting tqdm
  Using cached tqdm-4.55.1-py2.py3-none-any.whl (68 kB)
Building wheels for collected packages: configargparse
  Building wheel for configargparse (setup.py) ... done
  Created wheel for configargparse: filename=ConfigArgParse-1.2.3-py3-none-any.whl size=19327 sha256=6f397689ccbada490c331f4755fd89009914a26a109cdaa72736b172f43379aa
  Stored in directory: /home/alan/.cache/pip/wheels/8c/56/a5/1c051b2cca57d199fc048e2516424f24263cefd3ec2059990e
Successfully built configargparse
Installing collected packages: PyQt5-sip, tqdm, Send2Trash, PyQt5, configargparse, par2deep
Successfully installed PyQt5-5.15.2 PyQt5-sip-12.8.1 Send2Trash-1.5.0 configargparse-1.2.3 par2deep-1.9.5.1 tqdm-4.55.1
```

```
alan@microserver:~$ par2deep-env/bin/par2deep-cli -dir /data/sharedmedia/FilmAnimazione/
Traceback (most recent call last):
  File "par2deep-env/bin/par2deep-cli", line 8, in <module>
    sys.exit(main())
  File "/home/alan/par2deep-env/lib/python3.7/site-packages/par2deep/cli.py", line 38, in main
    print("Looking for files in",p2d.directory,"...")
AttributeError: 'par2deep' object has no attribute 'directory'
```

**Comment by alanfranz** [comment]
The target dir exists and is readable and writable by current user; in fact, I get the very same error when using just any directory.

**Comment by brenthuisman** [comment]
I didn't update the cli for the new directory stuff. But it appears it doesn't work reliably for the gui either, so I'm afraid you'll have to ask pypi for version 1.9.4, the last known good one. I'm working on a version that does not use par2cmdline anymore at all, because it's just hard to deal with.

Maybe I'll push 1.9.5.2 that reverts to 1.9.4 later today.

**Comment by brenthuisman** [comment]
I've removed releases after 1.9.4 from Pypi, which fixes this issue. Please reinstall and let me know if it does not work!
